"""empty message

Revision ID: e595d6611346
Revises: f6b3f59f2176
Create Date: 2016-09-23 16:58:03.007828

"""

# revision identifiers, used by Alembic.
revision = 'e595d6611346'
down_revision = 'f6b3f59f2176'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', sa.String(length=32), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_name')
    ### end Alembic commands ###
