"""empty message

Revision ID: f6b3f59f2176
Revises: 1659fe8ea64c
Create Date: 2016-09-23 16:33:05.395371

"""

# revision identifiers, used by Alembic.
revision = 'f6b3f59f2176'
down_revision = '1659fe8ea64c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    ### end Alembic commands ###
